### ISSUE TITLE
FTP Server based on go-storage

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/beyond-ftp#1]
## Description

FTP is the oldest network tool in the history of the Internet and is still widely used in many areas. 
This project will develop an FTP server based on [go-storage].

## Roadmap

- [ ] Implement behaviors by [go-service-ftp]
- [ ] Setup integration tests
- [ ] Add docs in [site](https://github.com/aos-dev/site)
- [ ] Add examples in [example](https://github.com/aos-dev/go-storage-example)

[go-storage]: https://github.com/aos-dev/go-storage
[go-service-ftp]: https://github.com/aos-dev/go-service-ftp

**Comment by Xuanwo** [comment]
Please take a look at https://github.com/qingstor/qsftpd

**Comment by Xuanwo** [comment]
@xiongjiwei is responsible for this issue.
